---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: twflix-ui
  labels:
    app: twflix-ui
    release: primary
spec:
  selector:
    matchLabels:
      app: twflix-ui
      release: primary
  template:
    metadata:
      labels:
        app: twflix-ui
        release: primary
    spec:
      containers:
      - name: twflix-ui
        image: aashishk7/demo-repeater:0.0.1
        env:
        - name: VERSION
          value: "twflix Demo Service Success Response"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
            limits:
              cpu: 100m
              memory: 50Mi
            requests:
              cpu: 50m
              memory: 20Mi
